apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  labels:
    app: capstone-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-deployment
    spec:
      containers:
        - image: razaqofficial/capstone
          imagePullPolicy: Always
          name: capstone-deployment
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP