---

- name: "update apt packages"
  become: true
  apt:
    update_cache: yes
    
- name: "update package cache"
  become: yes
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: true
    
- name: "Install zip and unzip"
  become: true
  apt:
    name: ["zip", "unzip"]
    state: latest
    update_cache: yes
    
- name: "Install nodejs and npm."
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
    
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    