---

- name: "Create app directory if it does not exist"
  become: true
  file:
    path: /home/ubuntu/app
    state: directory
    mode: 0775

- name: "unzip app directory"
  become: true
  unarchive:
    src: ~/project/app.zip
    dest: /home/ubuntu/app
    
- name: "start application"
  become: true
  shell: |
    cd /home/ubuntu/app
    npm i
    pm2 start npm --name server -- run start