---

- name: "deploy play"
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - APP_PORT: "{{ lookup('env','APP_PORT') }}"
    - NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    - VERSION: "{{ lookup('env','VERSION') }}"
    - DB_HOST: "{{ lookup('env','DB_HOST') }}"
    - DB_PORT: "{{ lookup('env','DB_PORT') }}"
    - DB_USER: "{{ lookup('env','DB_USER') }}"
    - DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
    - DB_NAME: "{{ lookup('env','DB_NAME') }}"

  pre_tasks:
    - name: "wait 100 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 100

  roles:
    - start-application